blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<tag_word>[\w\-]+)/$', views.by_tag, name='by_tag'),
    url(r'^(?P<year>[0-9]+)/(?P<month>[0-9]+)', views.archives, name='archives')
]

portfolio/urls.py
from django.conf.urls import url

from . import views

app_name = 'portfolio'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^portfolio/$', views.portfolio, name='portfolio'),
    url(r'^contact/$', views.contact, name='contact')
]

portfolio_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('portfolio.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(settings.ADMIN_URL, admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.paginator import Paginator


class Tag(models.Model):
    word = models.CharField(max_length=255)

    def __str__(self):
        return self.word


class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    author = models.ForeignKey(User, null=True, blank=True)
    # Many different tags can be associated with many different posts
    tags = models.ManyToManyField(Tag, blank=True)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': ''}))
    email = forms.EmailField(label='', widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    message = forms.CharField(label='', widget=forms.Textarea(attrs={'placeholder': 'Message'}), required=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post, Tag


def index(request):
    """
    Render part of all the posts by most recently created
    """
    latest_posts_list = Post.objects.filter(
        pub_date__lte=timezone.now()).order_by('-pub_date')
    paginator = Paginator(latest_posts_list, 8)

    page = request.GET.get('page')
    try:
        paginated_posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        paginated_posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page
        paginated_posts = paginator.page(paginator.num_pages)

    context = {'paginated_posts': paginated_posts}
    return render(request, 'blog/index.html', context)


def detail(request, post_id):
    """
    Render an individual post that has a pub_date in the past
    """
    post = get_object_or_404(
        Post.objects.filter(pub_date__lte=timezone.now()), pk=post_id)
    context = {'post': post}
    return render(request, 'blog/detail.html', context)


def by_tag(request, tag_word):
    """
    Render all the posts with specified tag
    """
    # Get queryset of Tag object with correct word. Probably a better way to do this
    tag = Tag.objects.filter(word=tag_word)
    posts = Post.objects.filter(tags__in=tag).order_by('-pub_date')

    paginator = Paginator(posts, 8)

    page = request.GET.get('page')
    try:
        paginated_posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        paginated_posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page
        paginated_posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'tag': tag, 'paginated_posts': paginated_posts}
    return render(request, 'blog/by_tag.html', context)


def archives(request, year, month):
    """
    Render all posts from specified year and month
    """
    posts = Post.objects.filter(pub_date__year=year, pub_date__month=month)

    paginator = Paginator(posts, 8)

    page = request.GET.get('page')
    try:
        paginated_posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        paginated_posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page
        paginated_posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'year': year, 'month': month,'paginated_posts': paginated_posts}
    return render(request, 'blog/archives.html', context)

portfolio/views.py
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.contrib import messages

from django.conf import settings

from .forms import ContactForm


def index(request):
    return render(request, 'portfolio/index.html')


def portfolio(request):
    return render(request, 'portfolio/portfolio.html')


def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            formatted_message = 'Name: {}\n\nEmail: {}\n\nMessage:{}'.format(name, email, message)
            try:
                send_mail('New Submission', formatted_message, email, [settings.EMAIL_DESTINATION])
            except BadHeaderError:
                return HttpResponse('Invalid header found')

            messages.add_message(request, messages.SUCCESS, 'Your message was sent! I\'ll get back to you shortly.', extra_tags='fade in')
            return redirect('portfolio:contact')

    return render(request, 'portfolio/contact.html', {'form': form})

blog/templates/blog/archives.html
{% extends "blog/base.html" %}
{% load markdown_deux_tags %}

{% block content %}
    <div class="col-sm-8">
    <h2>Browsing by archive date: {{ year }} {{ month }}</h2>

    {% for post in paginated_posts %}
    <div>
        <div>
            <a href="{% url 'blog:detail' post.id %}"><h2 class="blog-post-title">{{ post.title }}</h2></a>
            <p class="blog-post-meta">{{ post.pub_date|date:"F j Y" }} By {{ post.author.first_name}}</p>
        </div>
        <div>
            {{ post.body|markdown|truncatewords:200 }}

            {% if post.body|wordcount >= 200 %}
                <p class="text-center"><a class="read-more" href="{% url 'blog:detail' post.id %}">Read More</a></p>
            {% endif %}
        </div>
        <div>
        <p>
        {% if post.tags.all %}
        <i class="fa fa-tags fa-color fa-lg" aria-hidden="true"></i>
        {% endif %}
        {% for tag in post.tags.all %}
            <a class="tag" href="{% url 'blog:by_tag' tag %}">{{ tag }}</a>
        {% endfor %}
        </p>

        </div>

        <hr>
    </div>
    {% endfor %}
    
    {% if  paginated_posts.paginator.num_pages > 1 %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if paginated_posts.has_previous %}
                    <li><a href="?page={{ paginated_posts.previous_page_number }}">Prev</a></li>
            {% endif %}
            {% for page in paginated_posts.paginator.page_range %}
                <li class="{% if paginated_posts.number == page  %}active{% endif %}"><a href="?page={{page }}">{{ page }}</a></li>
            {% endfor %}

            {% if paginated_posts.has_next %}
                <li> <a href="?page={{ paginated_posts.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}

    </div>

    {% include "blog/sidebar.html" %}


{% endblock content %}

blog/templates/blog/base.html
{% load bootstrap3 %}
{% bootstrap_css %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog | Brandon Haakenson</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body class="blog-bg">
    
    {% include "blog/nav.html" %}


    <div class="container">
        <div class="blog-header text-center">
            <h1 class="blog-title"><a class="link-no-style" href="{% url 'blog:index' %}"><i class="fa fa-color fa-code" aria-hidden="true"></i> Brandon's Blog</a></h1>
            <p class="blog-description">Maybe one day I'll think of a better name</p>
            
        </div>
        {% block content %}
            
        {% endblock content %}
        
    </div>
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    {% bootstrap_javascript %}
    {# // <script src="{% static 'js/index.js' %}"></script> #}
</body>
</html>

blog/templates/blog/by_tag.html
{% extends "blog/base.html" %}
{% load markdown_deux_tags %}

{% block content %}
    <div class="col-sm-8">
    {# tag is a queryset of one so we need a for loop to access the tag word #}
    <h2>Browsing by the tag: {% for t in tag %}
        {{ t.word }}
    {% endfor %}</h2>

    {% for post in paginated_posts %}
    <div>
        <div>
            <a href="{% url 'blog:detail' post.id %}"><h2 class="blog-post-title">{{ post.title }}</h2></a>
            <p class="blog-post-meta">{{ post.pub_date|date:"F j Y" }} By {{ post.author.first_name}}</p>
        </div>
        <div>
            {{ post.body|markdown|truncatewords:200 }}

            {% if post.body|wordcount >= 200 %}
                <p class="text-center"><a class="read-more" href="{% url 'blog:detail' post.id %}">Read More</a></p>
            {% endif %}
        </div>
        <div>
            <p>
            {% if post.tags.all %}
            <i class="fa fa-tags fa-color fa-lg" aria-hidden="true"></i>
            {% endif %}
            {% for tag in post.tags.all %}
                <a class="tag" href="{% url 'blog:by_tag' tag %}">{{ tag }}</a>
            {% endfor %}
            </p>
        </div>
        <hr>
    </div>
    {% endfor %}

    {% if  paginated_posts.paginator.num_pages > 1 %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if paginated_posts.has_previous %}
                    <li><a href="?page={{ paginated_posts.previous_page_number }}">Prev</a></li>
            {% endif %}
            {% for page in paginated_posts.paginator.page_range %}
                <li class="{% if paginated_posts.number == page  %}active{% endif %}"><a href="?page={{page }}">{{ page }}</a></li>
            {% endfor %}

            {% if paginated_posts.has_next %}
                <li> <a href="?page={{ paginated_posts.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}

    </div>

    {% include "blog/sidebar.html" %}

{% endblock content %}

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load markdown_deux_tags %}
{% block content %}
<div>
    <div>
        <h2 class="blog-post-title">{{ post.title }}</h2>
        <p class="blog-post-meta">{{ post.pub_date|date:"F j Y" }} By {{ post.author.first_name}}</p>
    </div>
    <div class="blog-content">
        {{ post.body|markdown }}
    </div>
    
    <div class='tags-container'>
        <p>
        {% if post.tags.all %}
        <i class="fa fa-tags fa-color fa-lg" aria-hidden="true"></i>
        {% endif %}
        {% for tag in post.tags.all %}
            <a class="tag" href="{% url 'blog:by_tag' tag %}">{{ tag }}</a>
        {% endfor %}
        </p>
    </div>

    <hr>
</div>

{% load disqus_tags %}
{% disqus_show_comments "brandonhaakenson-me" %}
{% set_disqus_url object.get_absolute_url %}

{% endblock content %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load markdown_deux_tags %}

{% block content %}
    
<div class="col-sm-8">
{% for post in paginated_posts %}
<div>
    <div>
        <a href="{% url 'blog:detail' post.id %}"><h2 class="blog-post-title">{{ post.title }}</h2></a>
        <p class="blog-post-meta">{{ post.pub_date|date:"F j Y" }} By {{ post.author.first_name}}</p>
    </div>
    <div>
        {{ post.body|markdown|truncatewords:200 }}

        {% if post.body|wordcount >= 200 %}
            <p class="text-center"><a class="read-more" href="{% url 'blog:detail' post.id %}">Read More</a></p>
        {% endif %}
    </div>
    <div>
        <p>
        {% if post.tags.all %}
        <i class="fa fa-tags fa-color fa-lg" aria-hidden="true"></i>
        {% endif %}
        {% for tag in post.tags.all %}
            <a class="tag" href="{% url 'blog:by_tag' tag %}">{{ tag }}</a>
        {% endfor %}
        </p>
    </div>
    <hr>
</div>
{% endfor %}

{% if  paginated_posts.paginator.num_pages > 1 %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if paginated_posts.has_previous %}
                <li><a href="?page={{ paginated_posts.previous_page_number }}">Prev</a></li>
        {% endif %}
        {% for page in paginated_posts.paginator.page_range %}
            <li class="{% if paginated_posts.number == page  %}active{% endif %}"><a href="?page={{page }}">{{ page }}</a></li>
        {% endfor %}

        {% if paginated_posts.has_next %}
            <li> <a href="?page={{ paginated_posts.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}


</div>

{% include "blog/sidebar.html" %}

{% endblock content %}

blog/templates/blog/nav.html
    
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">Brandon Haakenson</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- data-toggle and collapse.in are to make the mobile menu close after a link is clicked -->
                <li><a href="{% url 'portfolio:portfolio' %}" data-toggle="collapse" data-target=".navbar-collapse.in">Projects</a></li>
                <li><a href="{% url 'blog:index' %}" data-toggle="collapse" data-target=".navbar-collapse.in">Blog</a></li>
                <li><a href="{% url 'portfolio:contact' %}" data-toggle="collapse" data-target=".navbar-collapse.in">Contact</a></li>
        </ul>
    </div>
</div>
</div>

blog/templates/blog/sidebar.html
<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <div class="sidebar-module sidebar-module-inset">
                <h3>About</h3>
                <p>I write about my programming learning experiences. Also I go through the steps I took to create some of my projects.</p>
            </div>
            <div class="sidebar-module">
                <h4><i class="fa fa-archive fa-color" aria-hidden="true"></i> Archives</h4>
                {% regroup latest_posts_list by pub_date|date:"Y" as year_list %}
                    {% for year in year_list %}
                        
                        {% regroup year.list by pub_date|date:"m" as month_list %}
                            {% for month in month_list %}
                                <a href="{% url 'blog:archives' year.grouper month.grouper %}">{{ year.grouper }} {{ month.grouper }}</a> <br>
                            {% endfor %}

                    {% endfor %}
            </div>
            <div class="sidebar-module">
                <h4><i class="fa fa-tags fa-color" aria-hidden="true"></i> Tags</h4>
                {% for tag in tags %}
                    <a class="tag" href="{% url 'blog:by_tag' tag.word %}">{{ tag.word }}</a>
                {% endfor %}
            </div>
        </div>

portfolio/templates/portfolio/base.html
{% load bootstrap3 %}
{% bootstrap_css %}


{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Brandon Haakenson | Web Developer</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body {% block background %}{% endblock background %}>
    
    {% include "portfolio/nav.html" %}


    
        {% block content %}
            
        {% endblock content %}
        
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    {% bootstrap_javascript %}
    {# // <script src="{% static 'js/index.js' %}"></script> #}
</body>
</html>

portfolio/templates/portfolio/contact.html
{% extends "portfolio/base.html" %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% block content %}

    
    <section id="contact">
        <div class="container">
            <h1 class="text-center"><i class="fa fa-color fa-envelope" aria-hidden="true"></i> Contact</h1>
            <div class="row">
            <div class="col-md-2"></div>
                <div class="col-md-8 text-center">
                    {% bootstrap_messages %}
                    <form action="" method="POST">
                        {% csrf_token %}

                        {% for field in form %}
                            <div>
                                {{ field.errors }}
                                {{ field }}
                            </div>
                        {% endfor %}

                        {% buttons %}
                            <button type="submit" class="btn btn-success submit">
                                Submit
                            </button>
                        {% endbuttons %}
                    </form>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </section>

{% endblock content %}

portfolio/templates/portfolio/index.html
{% extends "portfolio/base.html" %}

{% block background %}
    class='landing'
{% endblock background %}

{% block content %}
    
<div class="container fill">
    <div class="wrap">
        <div class="row">
            <div class="col-md-4 col-md-push-8">
                <img class="img-responsive rounded-img" src="/media/city_brandon.jpg" alt="photo of Brandon">
            </div>
            <div class="col-md-8 col-md-pull-4 about">
                <h1 class="text-center fadeIn fade-one">Hi, my name is Brandon</h1>
                <p class="fadeIn fade-two">I am a Computer Science student at IUPUI. Currently my skills include HTML, CSS, Javascript and Python. I like learning new skills and am always looking to improve. I am eager to work with and learn from a more experienced team of developers.</p>
                <div class="text-center fadeIn fade-two v-center">
                    <a href="https://github.com/haakensonb" target="_blank"><i class="fa fa-4x fa-github social" aria-hidden="true"></i></a>
                    <a class="projects-link" href="{% url 'portfolio:portfolio' %}">Check out my projects</a>
                    <a href="https://codepen.io/untamedhawk44/" target="_blank"><i class="fa fa-4x fa-codepen social" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

portfolio/templates/portfolio/nav.html
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a href="{% url 'portfolio:index' %}" class="navbar-brand">Brandon Haakenson</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- data-toggle and collapse.in are to make the mobile menu close after a link is clicked -->
                <li><a href="{% url 'portfolio:portfolio' %}" data-toggle="collapse" data-target=".navbar-collapse.in">Projects</a></li>
                <li><a href="{% url 'blog:index' %}" data-toggle="collapse" data-target=".navbar-collapse.in">Blog</a></li>
                <li><a href="{% url 'portfolio:contact' %}" data-toggle="collapse" data-target=".navbar-collapse.in">Contact</a></li>
        </ul>
    </div>
</div>
</div>

portfolio/templates/portfolio/portfolio.html
{% extends "portfolio/base.html" %}

{% block content %}
    <section id="projects">
    <h1 class="text-center">Projects</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-4 text-center">
                <div class="project well">
                    <img class="img-responsive center" src="/media/blog.png" alt="my blog">
                    <h3 class="underline">Simple Blog</h3>
                    <p>I built the blog portion of this site using Django and wrote about <a href="https://brandonhaakenson.me/blog/2/">my process here</a></p>
                    <a target="_blank" href="https://github.com/haakensonb/portfolio_django" class="src-link">View Source</a>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="project well">
                    <img class="img-responsive center" src="/media/ips-llc-2.png" alt="ips-llc landing page">
                    <h3 class="underline">Small Business Landing Page</h3>
                    <p>A front end site for displaying product and contact information. Built with SCSS</p>
                    <a target="_blank" href="http://ips-llc.net" class="src-link">View Source</a>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="project well">
                    <img class="img-responsive center" src="/media/pokemon.PNG" alt="who's that pokemon">
                    <h3 class="underline">Who's That Pokemon?</h3>
                    <p>A recreation of a classic Pokemon mini-game in which the viewer had to guess the pokemon by seeing a silhouette of it.</p>
                    <a target="_blank" href="https://github.com/haakensonb/whos_that_pokemon" class="src-link">View Source</a>
                </div>
            </div>
            
        </div>
        <div class="row">
            <div class="col-md-4 text-center">
                <div class="project well">
                    <img class="img-responsive center" src="/media/pomodoro.PNG" alt="pomodoro timer">
                    <h3 class="underline">Pomodoro Timer</h3>
                    <p>A timer built with Javascript based on the Pomodoro technique</p>
                    <a target="_blank" href="https://codepen.io/untamedhawk44/pen/MbZxXd" class="src-link">View Source</a>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="project well">
                    <img class="img-responsive center" src="/media/simon_says.PNG" alt="simon says">
                    <h3 class="underline">Simon Says</h3>
                    <p>A simple version of Simon Says using color sequences</p>
                    <a target="_blank" href="https://codepen.io/untamedhawk44/pen/xgXjqK" class="src-link">View Source</a>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="project well">
                    <img class="img-responsive center" src="/media/todo.PNG" alt="todo app">
                    <h3 class="underline">Todo App</h3>
                    <p>A simple Todo app made with vanilla Javascript</p>
                    <a target="_blank" href="https://github.com/haakensonb/todo_app" class="src-link">View Source</a>
                </div>
            </div>
            
        </div>
    </div>
</section>
{% endblock content %}